### ISSUE TITLE
Programmeerfout

### ISSUE THREAD

**Issue by jheijkamp** [hvtil/Wonderfoon_wemos_lolin#1]
De controller crasht door functies die niet goed zijn gedeclareerd. Zie bijvoorbeeld check112(). Deze zou een bool terug moeten geven maar doet dat niet. Dat wordt ook niet gevraagd door de roepende code. Ik heb van die functies een void gemaakt en het werkt weer prima
Groet,
Jan Heijkamp

**Comment by hvtil** [comment]
Dank voor het doorgeven, ik heb t aangepast
