### ISSUE TITLE
Code fout in function_general

### ISSUE THREAD

**Issue by user34756361233** [hvtil/Wonderfoon_wemos_lolin#2]
Function_general.ino bevat een fout stukje code waardoor na opstarten de telefoon altijd aangeeft dat er 112 gedraaid is. De Wemos crasht daarna en start weer opnieuw op. Het betreft de volgende code waarin **bool** vervangen moet worden door **void**

### FOUT
```
bool check112() {
  if (lastDialed[1] == 1 && lastDialed[2] == 1 && checkChangeTime())
  {

    if ( lastDialed[3] == 2 )
    {
      playAlarm();
      clearLastDialed();
    }
  }
}
```

### GOED
```
void check112() {
  if (lastDialed[1] == 1 && lastDialed[2] == 1 && checkChangeTime())
  {

    if ( lastDialed[3] == 2 )
    {
      playAlarm();
      clearLastDialed();
    }
  }
}
```

**Comment by hvtil** [comment]
Dank, ik heb het aangepast.
